### ISSUE TITLE
Discuss applicability of EZE

### ISSUE THREAD

**Issue by berndruecker** [camunda-community-hub/eze-java#13]
Thanks, @Lzgabel for this initiative. 

At the moment the EZE setup is nothing we support for any production use case - this has to be made very clear in the README. 

PS: I am personally skeptical if it is a good idea to push this idea now - when most projects would benefit from the discussion on how to work without an embedded engine.

**Comment by lzgabel** [comment]
Hi @berndruecker . Thank you for your recognition.

> At the moment the EZE setup is nothing we support for any production use case - this has to be made very clear in the README.

I'll add it later.

>  I am personally skeptical if it is a good idea to push this idea now.

In our edge computing cluster, due to the constraints of server resources and the need to provide the ability to automate processes, we can embed it in the application to manage it, and thus achieve greater benefits. Perhaps this reason may not be sufficient for now.🤔

**Comment by berndruecker** [comment]
I did a quick stab at it to make sure it is in there - feel free to adjust @Lzgabel
